- id: deploy-dashboard
  execute-command: /opt/cliproxyapi-dashboard/infrastructure/deploy.sh
  command-working-directory: /opt/cliproxyapi-dashboard/infrastructure
  pass-arguments-to-command:
    - source: payload
      name: no_cache
  trigger-rule:
    and:
      - match:
          type: value
          value: "{{DEPLOY_SECRET}}"
          parameter:
            source: header
            name: X-Deploy-Token

- id: deploy-dashboard-nocache
  execute-command: /opt/cliproxyapi-dashboard/infrastructure/deploy.sh
  command-working-directory: /opt/cliproxyapi-dashboard/infrastructure
  pass-arguments-to-command:
    - source: string
      name: "--no-cache"
  trigger-rule:
    and:
      - match:
          type: value
          value: "{{DEPLOY_SECRET}}"
          parameter:
            source: header
            name: X-Deploy-Token

- id: deploy-status
  execute-command: /bin/cat
  command-working-directory: /var/log/cliproxyapi
  pass-arguments-to-command:
    - source: string
      name: "/var/log/cliproxyapi/dashboard-deploy-status.json"
  trigger-rule:
    and:
      - match:
          type: value
          value: "{{DEPLOY_SECRET}}"
          parameter:
            source: header
            name: X-Deploy-Token

- id: deploy-log
  execute-command: /bin/cat
  command-working-directory: /var/log/cliproxyapi
  pass-arguments-to-command:
    - source: string
      name: "/var/log/cliproxyapi/dashboard-deploy.log"
  trigger-rule:
    and:
      - match:
          type: value
          value: "{{DEPLOY_SECRET}}"
          parameter:
            source: header
            name: X-Deploy-Token
